

export const GET_ORGANIZATION_MASTERDATA = 'GET_ORGANIZATION_MASTERDATA';

export const GET_USER_PROJECTS = 'GET_USER_PROJECTS';
export const GET_TIMESTAMPS = 'GET_TIMESTAMPS';
export const PUSH_DATA = 'PUSH_DATA';
export const GET_MASTERDATA = 'GET_MASTERDATA';
export const GET_PERMISSION_MASTER_DATA = 'GET_PERMISSION_MASTER_DATA';
export const GROUP_CHANGE = 'GROUP_CHANGE';
export const EXPORT_EXCEL = 'EXPORT_EXCEL';
export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION';
//#region Admin
export const GET_GROUPS = 'GET_GROUPS';
export const GET_COMPRANGES = 'GET_COMPRANGES';
export const GET_SALARY_RANGES = 'GET_SALARY_RANGES';
export const SAVE_SALARY_RANGES = 'SAVE_SALARY_RANGES';
export const DELETE_SALARY_RANGES = 'DELETE_SALARY_RANGES';
export const SAVE_GROUP = 'SAVE_GROUP';
export const CREATE_GROUP = 'CREATE_GROUP';
export const DELETE_GROUP = 'DELETE_GROUP';
export const UPDATE_GROUP_STATUS = 'UPDATE_GROUP_STATUS';
export const UPDATE_GROUP_LEADERSHIP = 'UPDATE_GROUP_LEADERSHIP';
export const GET_GROUP_HISTORY = 'GET_GROUP_HISTORY';
export const CLEAR_GROUP_HISTORY = 'CLEAR_GROUP_HISTORY';
export const GET_FUNCTIONAL_TITLES = 'GET_FUNCTIONAL_TITLES';

export const GET_PROJECT_DEFINED_FIELDS = 'GET_PROJECT_DEFINED_FIELDS';
export const GET_ROLES = 'GET_ROLES';
export const GET_ROLE_PERMISSIONS = 'GET_ROLE_PERMISSIONS';
export const GET_CLIENT_SETTINGS = 'GET_CLIENT_SETTINGS';
export const GET_PROJECT_VALUE_REPORT = 'GET_PROJECT_VALUE_REPORT';
export const PROJECT_CHANGE = 'PROJECT_CHANGE';

export const GET_BASELINE_DATA = 'GET_BASELINE_DATA';
export const CLEAR_BASELINE_DATA = 'CLEAR_BASELINE_DATA';
export const CALCULATE_CENTERDATA_CUBE = 'CALCULATE_CENTERDATA_CUBE';
export const CALCULATE_PERSONNEL_CUBE = 'CALCULATE_PERSONNEL_CUBE';
export const GET_BASELINE_UPLOAD_HISTORY = 'GET_BASELINE_UPLOAD_HISTORY';
export const CLEAR_BASELINE_UPLOAD_HISTORY = 'CLEAR_BASELINE_UPLOAD_HISTORY';
export const CREATE_COST_CENTER = 'CREATE_COST_CENTER';
export const UPDATE_COST_CENTER = 'UPDATE_COST_CENTER';
export const DELETE_COST_CENTER = 'DELETE_COST_CENTER';
export const CREATE_FINANCE_DATA = 'CREATE_FINANCE_DATA';
export const UPDATE_FINANCE_DATA = 'UPDATE_FINANCE_DATA';
export const DELETE_FINANCE_DATA = 'DELETE_FINANCE_DATA';
export const CREATE_PERSONNEL = 'CREATE_PERSONNEL';
export const UPDATE_PERSONNEL = 'UPDATE_PERSONNEL';
export const DELETE_PERSONNEL = 'DELETE_PERSONNEL';
export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const CREATE_CATEGORY_MAP = 'CREATE_CATEGORY_MAP';
export const UPDATE_CATEGORY_MAP = 'UPDATE_CATEGORY_MAP';
export const DELETE_CATEGORY_MAP = 'DELETE_CATEGORY_MAP';
export const SAVE_GROUP_CATEGORY_GLDOLLAR = 'SAVE_GROUP_CATEGORY_GLDOLLAR';
export const DELETE_GROUP_CATEGORY_GLDOLLAR = 'DELETE_GROUP_CATEGORY_GLDOLLAR';


export const GET_SCR_REPORTS = 'GET_SCR_REPORTS';
export const LOCK_SCR_REPORTS = 'LOCK_SCR_REPORTS';
export const UNLOCK_SCR_REPORTS = 'UNLOCK_SCR_REPORTS';
export const REARRANGE_SCR_REPORTS = 'REARRANGE_SCR_REPORTS';
export const PRINT_SCR_REPORTS = 'PRINT_SCR_REPORTS';
//#endregion

//#region Group Admin 
export const CREATE_GROUPSUMMARYTEXT = 'CREATE_GROUPSUMMARYTEXT';
export const UPDATE_GROUPSUMMARYTEXT = 'UPDATE_GROUPSUMMARYTEXT';
export const DELETE_GROUPSUMMARYTEXT = 'DELETE_GROUPSUMMARYTEXT';
export const ARRANGE_GROUPSUMMARY = 'ARRANGE_GROUPSUMMARY';
export const SAVE_FOCUSAREA = 'SAVE_FOCUSAREA';
export const GET_FOCUSAREA_USAGECOUNT = 'GET_FOCUSAREA_USAGECOUNT';
export const RESET_FOCUSAREA_USAGECOUNT = 'RESET_FOCUSAREA_USAGECOUNT';
export const DELETE_FOCUSAREA = 'DELETE_FOCUSAREA';
export const ARRANGE_FOCUSAREAS = 'ARRANGE_FOCUSAREAS';
export const SAVE_FOCUSAREA_LEADERS = 'SAVE_FOCUSAREA_LEADERS';
export const UPDATE_GROUP_PLANLOCK = 'UPDATE_GROUP_PLANLOCK';
export const UPDATE_GROUP_IDEATIMINGENABLE = 'UPDATE_GROUP_IDEATIMINGENABLE';
export const GET_GROUPADMIN_LEADERSHIP = 'GET_GROUPADMIN_LEADERSHIP';
export const SAVE_LEADERSHIP_ROLE_PERMISSION = 'SAVE_LEADERSHIP_ROLE_PERMISSION';
export const REMOVE_LEADERSHIP_ROLE_PERMISSION = 'REMOVE_LEADERSHIP_ROLE_PERMISSION';
export const SAVE_CUSTOMFIELD = 'SAVE_CUSTOMFIELD';
export const DELETE_CUSTOMFIELD = 'DELETE_CUSTOMFIELD';
export const UPLOAD_SCR_REPORT = 'UPLOAD_SCR_REPORT';
export const DELETE_SCR_REPORT = 'DELETE_SCR_REPORT';
export const SCR_REPORT_DELETE = 'SCR_REPORT_DELETE';
export const SCR_REPORT_CTM_APPROVAL = 'SCR_REPORT_CTM_APPROVAL';
export const SCR_REPORT_REMOVE_CTM_APPROVAL = 'SCR_REPORT_REMOVE_CTM_APPROVAL';
export const SCR_REPORT_PP_APPROVAL = 'SCR_REPORT_PP_APPROVAL';
export const SCR_REPORT_REMOVE_PP_APPROVAL = 'SCR_REPORT_REMOVE_PP_APPROVAL';

export const GET_SESSIONS = 'GET_SESSIONS';
export const CREATE_SESSION = 'CREATE_SESSION';
export const SESSION_LIST_SORT = 'SESSION_LIST_SORT';
export const SAVE_PARTICIPANTS = 'SAVE_PARTICIPANTS';
export const UPDATE_SESSION = 'UPDATE_SESSION';
export const IS_SHOW_ARCHIVED_SESSIONS = 'IS_SHOW_ARCHIVED_SESSIONS';
//#endregion

//#region User Admin
export const GET_USERS = 'GET_USERS';
export const GET_USER_MFA_ENROLLMENTS = 'GET_USER_MFA_ENROLLMENTS';
export const ENABLE_GETUSER_LOADING = 'ENABLE_GETUSER_LOADING';
export const CREATE_PERSONNEL_FROM_USERS = 'CREATE_PERSONNEL_FROM_USERS';
export const GET_ADMIN_USERS = 'GET_ADMIN_USERS';
export const GET_USER_PERMISSIONS = 'GET_USER_PERMISSIONS';
export const TOGGLE_PERMISSION_EXPAND_COLLAPSE = 'TOGGLE_PERMISSION_EXPAND_COLLAPSE';
export const GET_SELECTED_USER_PERMISSIONS = 'GET_SELECTED_USER_PERMISSIONS';
export const GET_SELECTED_ELEMENT_PERMISSION = 'GET_SELECTED_ELEMENT_PERMISSION';
export const CHANGE_PERMISSION_VIEW = 'CHANGE_PERMISSION_VIEW';
export const CHANGE_PERMISSION_TYPE = 'CHANGE_PERMISSION_TYPE';
export const SAVE_ROLE_PERMISSION = 'SAVE_ROLE_PERMISSION';
export const REMOVE_ROLE_PERMISSION = 'REMOVE_ROLE_PERMISSION';

export const GET_CONNECTIONS = 'GET_CONNECTIONS';
export const GET_USER_HISTORY = 'GET_USER_HISTORY';
export const CLEAR_USER_HISTORY = 'CLEAR_USER_HISTORY';
export const DELETE_ADMIN_USERS = 'DELETE_ADMIN_USERS';
export const SAVE_ADMIN_USERS = 'SAVE_ADMIN_USERS';
export const INVITE_USERS = 'INVITE_USERS';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CREATE_USER = 'CREATE_USER';
export const ADD_USER = 'ADD_USER';
export const REMOVE_USER = 'REMOVE_USER';
export const CREATE_AUTH0_USER = 'CREATE_AUTH0_USER';
export const INVITE_AUTH0_USER = 'INVITE_AUTH0_USER';
export const CHANGE_AUTH0_USER_PASSWORD = 'CHANGE_AUTH0_USER_PASSWORD';
export const CHANGE_AUTH0_USER_MFA = 'CHANGE_AUTH0_USER_MFA';
export const CHANGE_AUTH0_USER_MFA_LOG = 'CHANGE_AUTH0_USER_MFA_LOG';
export const RESET_AUTH0_USER_MFA = 'RESET_AUTH0_USER_MFA';
export const RESET_AUTH0_USER_MFA_LOG = 'RESET_AUTH0_USER_MFA_LOG';

//#endregion

//#region Baseline
export const BL_GROUP_CHANGE = 'BL_GROUP_CHANGE';
export const GET_BASELINESUMMARY = 'GET_BASELINESUMMARY';
export const GET_FUNCTIONALTITLEMAP_DATA = 'GET_FUNCTIONALTITLEMAP_DATA';
export const MAP_JOBTITLE_FT = 'MAP_JOBTITLE_FT';
export const ASSIGN_PERSONNEL_FT = 'ASSIGN_PERSONNEL_FT';
export const RESET_PERSONNEL_FT = 'RESET_PERSONNEL_FT';
export const SAVE_FUNCTIONALTITLE = 'SAVE_FUNCTIONALTITLE';
export const DELETE_FUNCTIONALTITLE = 'DELETE_FUNCTIONALTITLE';
//#endregion

//#region Idea
export const GET_IDEA_DATA = 'GET_IDEA_DATA';
export const IDEAGROUP_LIST_SORT = 'IDEAGROUP_LIST_SORT';
export const SCR_SORT_IDEAGROUP = 'SCR_SORT_IDEAGROUP';
export const TOGGLE_CHECKBOX_IDEAGROUP = 'TOGGLE_CHECKBOX_IDEAGROUP';
export const TOGGLE_ALL_CHECKBOX_IDEAGROUP_ONEPAGE = 'TOGGLE_ALL_CHECKBOX_IDEAGROUP_ONEPAGE';
export const UNCHECK_ALL_CHECKBOX_IDEAGROUP = 'UNCHECK_ALL_CHECKBOX_IDEAGROUP';
export const GET_IDEA_DETAIL_DATA = 'GET_IDEA_DETAIL_DATA';
export const SET_IDEAGROUP_SORTING_ONVIEWCHANGE = 'SET_IDEAGROUP_SORTING_ONVIEWCHANGE';
export const GET_IDEAIDS_BY_CATEGORIES = 'GET_IDEAIDS_BY_CATEGORIES';
export const GET_IDEAIDS_BY_FUNCTIONALTITLES = 'GET_IDEAIDS_BY_FUNCTIONALTITLES';
export const GET_SHAREDANDTRANSFERED_IDEA_DATA = 'GET_SHAREDANDTRANSFERED_IDEA_DATA';
export const CREATE_IDEA_SIMPLIFIED_EMPTY_IDEA = 'CREATE_IDEA_SIMPLIFIED_EMPTY_IDEA';
export const CLEAR_NEW_IDEAS = 'CLEAR_NEW_IDEAS';
//#endregion

//#region Personnel
export const GET_PERSONNEL_SEARCH = 'GET_PERSONNEL_SEARCH';
export const CLEAR_PERSONNEL_SEARCH = 'CLEAR_PERSONNEL_SEARCH';
//#endregion

//#region Users
export const GET_USER_SEARCH = 'GET_USER_SEARCH';
export const CLEAR_USER_SEARCH = 'CLEAR_USER_SEARCH';
//#endregion

//#region LineItems
export const GET_ANNUAL_VALUES = 'GET_ANNUAL_VALUES';
//#endregion

//#region Dashboard
export const GET_DASHBOARD_DATA = 'GET_DASHBOARD_DATA';
export const GET_DASHBOARD_OTHER_DATA = 'GET_DASHBOARD_OTHER_DATA';
export const DASHBOARD_PHASE_CHANGE = 'DASHBOARD_PHASE_CHANGE';
export const DASHBOARD_VALUE_TYPE_CHANGE = 'DASHBOARD_VALUE_TYPE_CHANGE';
export const DASHBOARD_RECOMMENDATION_TYPE_CHANGE = 'DASHBOARD_RECOMMENDATION_TYPE_CHANGE';
export const DASHBOARD_DECISION_TYPE_CHANGE = 'DASHBOARD_DECISION_TYPE_CHANGE';
export const DASHBOARD_FILTER = 'DASHBOARD_FILTER';
//#endregion

//#region IdeaGroup
export const UPDATE_IDEAGROUP_DATA = 'UPDATE_IDEAGROUP_DATA';
//#endregion

export const SHOW_CREATE_NEW_ITEM_NOTIFICATION = 'SHOW_CREATE_NEW_ITEM_NOTIFICATION';
export const HIDE_MULTI_NOTIFY = 'HIDE_MULTI_NOTIFY';
export const SHOW_MULTI_NOTIFY = 'SHOW_MULTI_NOTIFY';

//#region Session Ideas
export const GET_SESSION_IDEA_DATA = 'GET_SESSION_IDEA_DATA';
export const CREATE_SESSION_IDEA = 'CREATE_SESSION_IDEA';
export const UPDATE_SESSION_IDEA = 'UPDATE_SESSION_IDEA';
export const BULK_UPDATE_SESSION_IDEA = 'BULK_UPDATE_SESSION_IDEA';
export const DELETE_SESSION_IDEA = 'DELETE_SESSION_IDEA';
export const DELETE_BULK_SESSION_IDEAS = 'DELETE_BULK_SESSION_IDEAS';
export const MOVE_BULK_SESSION_IDEAS = 'MOVE_BULK_SESSION_IDEAS';
//#endregion

//#region User Note
export const CURRENT_GROUP_TAB_CLICK = 'CURRENT_GROUP_TAB_CLICK';
export const SORT_USER_NOTE = 'SORT_USER_NOTE';
export const ON_RENDER_IDEALIST = 'ON_RENDER_IDEALIST';
export const SORT_USERNOTE_ON_EXPEND_IDEA = 'SORT_USERNOTE_ON_EXPEND_IDEA';
export const COLLAPSE_EXPEND_IDEA = 'COLLAPSE_EXPEND_IDEA';
export const SORT_USERNOTE_ON_IMPLEMENTATION_VIEWS = 'SORT_USERNOTE_ON_IMPLEMENTATION_VIEWS';
export const USERNOTES_TIMESTAMP = 'USERNOTES_TIMESTAMP';
//#endregion

//#region Advanced Search
export const ADVANCED_SEARCH_RESULT_LOADER = 'ADVANCED_SEARCH_RESULT_LOADER';
export const FETCH_ADVANCED_SEARCH_RESULT = 'FETCH_ADVANCED_SEARCH_RESULT';
export const FETCH_ADVANCED_SEARCH_GO_IDEA_RESULT = 'FETCH_ADVANCED_SEARCH_GO_IDEA_RESULT';
export const CLEAR_ADVANCED_RESULTS_DATA = 'CLEAR_ADVANCED_RESULTS_DATA';

export const SAVE_PROJECT_CONFIG = 'SAVE_PROJECT_CONFIG';
export const GET_PROJECT_CONFIG_HISTORY = 'GET_PROJECT_CONFIG_HISTORY';
export const CLEAR_PROJECT_CONFIG_HISTORY = 'CLEAR_PROJECT_CONFIG_HISTORY';

//#region Timing Scenarios
export const GET_TIMING_SCENARIOS = 'GET_TIMING_SCENARIOS';
export const CREATE_TIMING_SCENARIO = 'CREATE_TIMING_SCENARIO';
export const UPDATE_TIMING_SCENARIO = 'UPDATE_TIMING_SCENARIO';
export const GET_TIMING_SCENARIO_SESSION_PROFORMA_DATA = 'GET_TIMING_SCENARIO_SESSION_PROFORMA_DATA';
export const TIMING_SCENARIO_SESSION_PROFORMA_PAGE_CHANGE = 'TIMING_SCENARIO_SESSION_PROFORMA_PAGE_CHANGE';
export const TIMING_SCENARIO_SESSION_PROFORMA_RESET_PAGE = 'TIMING_SCENARIO_SESSION_PROFORMA_RESET_PAGE';
export const TIMING_SCENARIO_SESSION_TOGGLE_CHECKBOX = 'TIMING_SCENARIO_SESSION_TOGGLE_CHECKBOX';
export const TIMING_SCENARIO_SESSION_TOGGLE_EXPAND = 'TIMING_SCENARIO_SESSION_TOGGLE_EXPAND';
export const TIMING_SCENARIO_SUMMARY_SET_DRAGGED_AXIS = 'TIMING_SCENARIO_SUMMARY_SET_DRAGGED_AXIS';

//#endregion
